#!/usr/bin/env bash
# This script displays numbers from 1 to 20 with specific messages for the 4th, 9th, and 7th iterations using case statements.

count=1
while [ $count -le 20 ] 
do
	echo "$count"
	case $count in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
	esac
	((count++))
done
